// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqILLgdR5psuOONq2oO4WYbqMItkyjRUE',
    appId: '1:158649321104:web:cbe894cd62108ec48d7a15',
    messagingSenderId: '158649321104',
    projectId: 'saidaelajimiflutterapp',
    authDomain: 'saidaelajimiflutterapp.firebaseapp.com',
    storageBucket: 'saidaelajimiflutterapp.firebasestorage.app',
    measurementId: 'G-87FRRW0Z65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPKIheX5zzWjJGMZ0aO9sxyXr_0H5JoOI',
    appId: '1:158649321104:android:b3dbcf2b935b7a028d7a15',
    messagingSenderId: '158649321104',
    projectId: 'saidaelajimiflutterapp',
    storageBucket: 'saidaelajimiflutterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AZPLWVbydgyFWkp3xTYCRs6l8HEZKSA',
    appId: '1:158649321104:ios:24a5bdf47530f4558d7a15',
    messagingSenderId: '158649321104',
    projectId: 'saidaelajimiflutterapp',
    storageBucket: 'saidaelajimiflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.smartAppSaidaelajimiG8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AZPLWVbydgyFWkp3xTYCRs6l8HEZKSA',
    appId: '1:158649321104:ios:24a5bdf47530f4558d7a15',
    messagingSenderId: '158649321104',
    projectId: 'saidaelajimiflutterapp',
    storageBucket: 'saidaelajimiflutterapp.firebasestorage.app',
    iosBundleId: 'com.example.smartAppSaidaelajimiG8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqILLgdR5psuOONq2oO4WYbqMItkyjRUE',
    appId: '1:158649321104:web:747d3c6c644b5a308d7a15',
    messagingSenderId: '158649321104',
    projectId: 'saidaelajimiflutterapp',
    authDomain: 'saidaelajimiflutterapp.firebaseapp.com',
    storageBucket: 'saidaelajimiflutterapp.firebasestorage.app',
    measurementId: 'G-DRB26XKHSF',
  );
}
